Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('blog_admin/', include('blog_admin.urls')),


]

Blog/blogapp/urls.py
from django.urls import path,include
from . import views 
urlpatterns = [
    path('',views.HomeView.as_view(),name="home" ),

    path('accounts/',include('allauth.urls')),
    
    path('article/<int:pk>',views.ArticleView.as_view(),name="article" ),
    path('article/<int:pk>/comment',views.AddCommentView.as_view(),name="add_comment" ),
    path('add_post/',views.AddPostView.as_view(),name="add_post" ),
    path('add_category/',views.AddCategoryView.as_view(),name="addCategory" ),
    path('article/edit/<int:pk>',views.EditPostView.as_view(),name="edit_post" ),
    path('article/delete/<int:pk>',views.DeletePostView.as_view(),name="delete_post" ),
    # path('category/<str:cats>',views.CategoryView,name="category" ),
    path('category/<int:cats>',views.CategoryView.as_view(),name="category" ),
    path('search',views.search_post,name="search" ),
    path('my_posts',views.MyPostView.as_view(),name="my_posts"),
    

]

Blog/blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime,date
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home')

    class Meta:
        verbose_name_plural = 'categories'

class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    body = models.TextField()
    # publised_date = models.DateTimeField(auto_now_add=True)
    publish_date = models.DateField(auto_now_add=True)
    # category = models.CharField(max_length=100)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)

    def __str__(self):
        return self.title +' | '+ str(self.author)

    def get_absolute_url(self):
        return reverse('article',args=(str(self.id),))


class Comment(models.Model):
    post = models.ForeignKey(Post,related_name='comments',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='comments',on_delete=models.CASCADE)
    # name = models.CharField(max_length=255)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.post.title} - {self.user.first_name} {self.user.last_name}'

    def get_absolute_url(self):
        return reverse('article',args=(str(self.post.id),))

Blog/blogapp/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets
from .models import Comment, Post,Category

# choices = [('coding','coding'),('lifestyle','lifestyle'),('sport','sport'),('health','health'),]
choices = Category.objects.all().values_list('name','name')
# print(choices)
choices_list=[]

for item in choices:
    choices_list.append(item)
# print(choices_list)


class PostForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super(PostForm, self).__init__(*args, **kwargs)
        # there's a `fields` property now
        self.fields['author'].required = False
    
    class Meta:
        model = Post
        fields = ['title','author','category','body']

        widgets={
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            # 'author' : forms.Select(attrs={'class':'form-control'}),
            'author' : forms.HiddenInput(attrs={'class':'form-control','required': False}),
            # 'category':forms.Select(choices=choices,attrs={'class':'form-control'}),
            'category':forms.Select(choices=choices_list,attrs={'class':'form-control'}),
            'body' : forms.Textarea(attrs={'class':'form-control'}),
        }

class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields =['title','body']

        widgets={
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            # 'author' : forms.Select(attrs={'class':'form-control'}),
            'body' : forms.Textarea(attrs={'class':'form-control'})
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields =['body']

        widgets={
            # 'user' : forms.TextInput(attrs={'class':'form-control'}),
            # 'author' : forms.Select(attrs={'class':'form-control'}),
            'body' : forms.Textarea(attrs={'class':'form-control'})
        }

Blog/blogapp/views.py
from django.db import models
from django.db.models import fields
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from django.views.generic import ListView,DetailView, CreateView, UpdateView, DeleteView, TemplateView
from .models import Post,Category,Comment
from .forms import PostForm,EditForm,CommentForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404,HttpResponseForbidden
from django.core.exceptions import PermissionDenied
from django_filters.rest_framework import DjangoFilterBackend
import django_filters
from .mixins import CheckReaderGroupMixin,CheckEditorGroupMixin, CheckCommentorGroupMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin


# Create your views here.
def home(request):
    return render(request,"blogapp/home.html")
    # return HttpResponse("Hi")

class PostFilter(django_filters.FilterSet):
    # start_date = django_filters.DateFilter(field_name='publish_date',lookup_expr='gte')
    # end_date = django_filters.DateFilter(field_name='publish_date',lookup_expr='lte')
    # range = django_filters.DateFromToRangeFilter (field_name='publish_date',lookup_expr='lte')
    body = django_filters.CharFilter(field_name='body',lookup_expr='icontains')
    # category = django_filters.CharFilter(field_name='category',lookup_expr='icontains')
    class Meta:
        model = Post
        fields="__all__"
        exclude=['body','publish_date']


class HomeView(ListView):
    # LOGIN_URL = reverse_lazy('login')

    model = Post
    template_name = 'blogapp/home.html'
    ordering = ['-publish_date']
    paginate_by= 5 # 5 items per page
    paginate_orphans = 1 
    # filter_backends = [DjangoFilterBackend]
    # filterset_fileds=['category']
    
    filterset_class = PostFilter
    def get_template_names(self):
        # if self.request.user.is_superuser:
        #     template_name = 'blog_admin/index.html'
        # else:
        #     template_name = 'blogapp/home.html'
        template_name = 'blogapp/home.html'
        return template_name



    def get_queryset(self):
        keyword = self.request.GET.get('search','')
        if keyword:
            posts = Post.objects.filter(body__contains=keyword)
            return posts
        # myFilter = PostFilter(self.request.GET,self.get_queryset())
        return super().get_queryset()
    
    def get_context_data(self,*args, **kwargs):
        myFilter = PostFilter(self.request.GET,self.get_queryset())
        context = super().get_context_data(*args,**kwargs)
        context['categories']= Category.objects.all()
        context['myFilter']= myFilter  
        context['object_list']= myFilter.qs  
        return context

    def paginate_queryset(self, queryset, page_size):
        try:
            return super().paginate_queryset(queryset, page_size)
        except Http404:
            self.kwargs['page']=1
            return super().paginate_queryset(queryset, page_size)




# def post_filter(request):
# 	posts= Post.object.all()
# 	filter = PostFilter(request.GET, queryset = posts)
# 	return render(request, 'blogapp/home.html', {'object_list' : filter})



class ArticleView(LoginRequiredMixin,DetailView):
    model = Post
    template_name = 'blogapp/article.html'

class AddPostView(SuccessMessageMixin,CheckEditorGroupMixin,CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blogapp/add_post.html'
    success_message = "Post created successfully"

    # fields = '__all__'
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.author = self.request.user
        # self.object = form.save()
        instance.save()
        # do something with self.object
        # remember the import: from django.http import HttpResponseRedirect
        return HttpResponseRedirect(instance.get_absolute_url())

    
class EditPostView(SuccessMessageMixin,CheckEditorGroupMixin,UpdateView):
    model = Post
    template_name = 'blogapp/edit_post.html'
    # fields=['title','body']
    form_class = EditForm
    success_message = "Post updated successfully"

    
    # def dispatch(self, request, *args, **kwargs):
    #     if not request.user.has_perm('blog_permission.blog_edit'):
    #         raise PermissionDenied()
    #     return super(EditPostView, self).dispatch(request, *args, **kwargs)

    def get_object(self, *args, **kwargs):
        obj = super(EditPostView, self).get_object(*args, **kwargs)
        if obj.author.id == self.request.user.id:
            return obj   
        raise PermissionDenied #Http404
        

    

class DeletePostView(SuccessMessageMixin,CheckEditorGroupMixin,DeleteView):
    model = Post
    template_name = 'blogapp/delete_confirm.html'
    success_url=reverse_lazy('home')
    success_message = "Post deleted successfully"

class AddCategoryView(SuccessMessageMixin,CheckEditorGroupMixin,CreateView):
    model = Category
    # form_class = PostForm
    template_name = 'blogapp/add_category.html'
    fields = '__all__'
    # success_url=reverse_lazy('home')
    success_message = "Category added successfully"


# def CategoryView(request,cats):
#     cats = cats.replace('-',' ')
#     category_posts = Post.objects.filter(category=cats).order_by("-publish_date")
#     return render(request,'blogapp/categories.html',{'category':cats.title(),'category_posts':category_posts})


class CategoryView(ListView):
    model = Post
    template_name = 'blogapp/home.html'
    # ordering = ['-id']
    ordering = ['-publish_date']
    filterset_class = PostFilter
    
    def get_queryset(self,*args, **kwargs):
        cats = self.kwargs['cats']
        category_posts = Post.objects.filter(category=cats).order_by("-publish_date")
        return category_posts

    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['categories']= Category.objects.all()

        myFilter = PostFilter(self.request.GET,self.get_queryset())
        context['myFilter']= myFilter  
        context['object_list']= myFilter.qs 
        return context

# Add comment
class AddCommentView(SuccessMessageMixin,CheckCommentorGroupMixin,CreateView):
    model = Comment
    form_class = CommentForm
    # fields = '__all__'
    template_name = 'blogapp/add_comment.html'
    ordering = ['-date_added']
    success_message = "Comment added successfully"

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        form.instance.user = self.request.user
        return super().form_valid(form)


# Search Post
def search_post(request):
    if request.method == 'POST':
        keyword = request.POST['search']
        posts = Post.objects.filter(body__contains=keyword)
        return render(request,'blogapp/home.html',{'object_list':posts})
    return render(request,'blogapp/home.html')


class MyPostView( CheckEditorGroupMixin ,ListView):
    model = Post
    template_name = 'blogapp/myposts.html'
    ordering = ['-publish_date']
    
    filterset_class = PostFilter

    def get_queryset(self):
        posts = Post.objects.filter(author=self.request.user)
        return posts
    
    def get_context_data(self,*args, **kwargs):
        myFilter = PostFilter(self.request.GET,self.get_queryset())
        context = super().get_context_data(*args,**kwargs)
        context['categories']= Category.objects.all()
        context['myFilter']= myFilter  
        context['object_list']= myFilter.qs  
        return context
        

class SocialLoginTemplateView(TemplateView):
    template_name="blogapp/social_login.html"

Blog/blogapp/templates/blogapp/add_category.html
{% extends 'blogapp/base.html' %}
{% block title %}Add Category{% endblock %}
{% block content %}
<div class="text-center mt-3">
    <h1 >Add Post Category</h1>
    <div class="form-group mt-3">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Add"> 
            <a href="{% url 'home' %}" class="btn btn-secondary">Back</a>
        </form>
    </div>
</div>
  
    

       
 
{% endblock %}

Blog/blogapp/templates/blogapp/add_comment.html
{% extends 'blogapp/base.html' %}
{% block title %}Add Comment{% endblock %}
{% block content %}
    <h1>Add Comment on Post</h1>
    <div class="form-group">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Add Comment"> 
            <a href="{% url 'home' %}" class="btn btn-secondary">Back</a>
        </form>
    </div>
    

       
 
{% endblock %}

Blog/blogapp/templates/blogapp/add_post.html
{% extends 'blogapp/base.html' %}
{% block title %}Add Post{% endblock %}
{% block content %}
<div>
    <h1 class="text-center mt-3" >Add Blog Post</h1>
    <div class="form-group bg-light mt-5">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Add"> 
            <a href="{% url 'home' %}" class="btn btn-secondary">Back</a>
        </form>
    </div>
</div>

       
 
{% endblock %}

Blog/blogapp/templates/blogapp/admin_home.html
Hi admin,Welcome

Blog/blogapp/templates/blogapp/article.html
{% extends 'blogapp/base.html' %}
{% block title %}Post-{{post.title}}{% endblock %}
{% block content %}
    <div class="text-center mt-3">
    <h1 class="text-center mt-3" >{{post.title}}</h1>
    <small>By: {{post.author.first_name}} {{post.author.last_name}} - {{post.publish_date}}</small>
</div>
    <hr>
    <br/>
       <p>
        {{post.body|safe}}
       </p> 
       <a href="{% url 'home' %}" class="btn btn-secondary">Back</a>
       {% if user.is_authenticated and user.id == post.author.id %}

        <a href="{% url 'edit_post' post.pk %}" class="btn btn-secondary">Edit</a>
        <a href="{% url 'delete_post' post.pk %}" class="btn btn-secondary">Delete</a>
        {% endif %}

        <br>
        <br>
        
        <hr>
        <h2>Add Comment</h2>
        <div class="form-group">
            <form action="{% url 'add_comment' post.id %}" method="POST">
                {% csrf_token %}
                <!-- {{ form.as_p }} -->
                <textarea name="body" cols="40" rows="10" class="form-control" required="" id="id_body" style="height: 150px;"></textarea>
                <br>
                <input type="submit" class="btn btn-primary" value="Add Comment"> 
            </form>
        </div>       

        <h2 class="text-center mt-3">Comments</h2>
        {% if not post.comments.all %}
            <p class="text-center mt-3">No Comments yet... </p>
        {%else%}
            {% for comment in post.comments.all %}
            <strong>
                {{comment.user.username}}-{{comment.date_added}}
            </strong>    
             <br>
                <p>
                    {{comment.body}}
                </p>
                
            {% endfor %}
        {%endif%}

      
 
{% endblock %}

Blog/blogapp/templates/blogapp/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">My Blog App</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            
            <!-- {% if categories %}
            <li class="nav-item dropdown mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Categories
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for cat in categories %}
                <li><a class="dropdown-item" href="{% url 'category' cat.id %}">{{cat}}</a></li>
                {% endfor %}
              </ul>
            </li>
            {% endif %} -->

           

            {% if user.is_authenticated %}

            {% if user.is_superuser %}
            <li class="nav-item mx-1">
              <a class="nav-link active" aria-current="page" href="{% url 'admin_home' %}">Admin Home</a>
            </li>
            <li class="nav-item mx-1">
              <a class="nav-link active" href="{% url 'home' %}">Blogs</a>
            </li>
            <!-- <li class="nav-item mx-1">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Visit Site</a>
            </li> -->
            {%else%}
            <li class="nav-item mx-1">
              <a class="nav-link active"  href="{% url 'home' %}">Blogs</a>
            </li>
            {% endif %}
            <li class="nav-item mx-1">
              <a class="nav-link" href="{% url 'add_post' %}">Add Post</a>
            </li>
            <li class="nav-item mx-1">
              <a class="nav-link" href="{% url 'addCategory' %}">Add Category</a>
            </li>

            <li class="nav-item mx-1">
              <a class="nav-link" href="{% url 'edit_profile' %}">Edit Profile</a>
            </li>
            <li class="nav-item mx-1">
              <a class="nav-link" href="{% url 'my_posts' %}">My Posts</a>
            </li>
            <li class="nav-item mx-1">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            <li class="nav-item mx-1">
              <a class="nav-link" href="">Welcome {{user.username}}</a>
            </li>
            {%else%}
            <li class="nav-item mx-1">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item mx-1">
              <a class="nav-link " href="{% url 'register' %}">Register</a>
            </li>
            <li class="nav-item mx-1">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %} 
        </ul>
          <!-- <form class="d-flex" method="GET" action="">
            
            <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form> -->
        </div>
      </div>
    </nav>
    <div>
      {% if messages %}
        {% for message in messages %}
            <div class="text-center alert alert-{{ message.tags }}">
                {{ message|safe }}
            </div>
        {% endfor %}
      {% endif %}
    </div>
    {% block content %}

    {% endblock %}

    <style>
      a:link {
        text-decoration: none;
      }
    </style>
  </div>

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    -->
</body>

</html>

Blog/blogapp/templates/blogapp/categories.html
{% extends 'blogapp/base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    

    <h1>{{category}}</h1>

    {% if category_posts %}
        <ul> 
            {% for post in category_posts %}
                <li> <a href="{% url 'article' post.id %}">{{post.title}}</a> - {{post.author.first_name}} {{post.author.last_name}}<br>
                {{post.body|safe|truncatewords:80}}...</li>
            {% endfor %}
        </ul>
    {%else%}
        <p>No posts exists...</p>
    {% endif %}

{% endblock %}    

Blog/blogapp/templates/blogapp/delete_confirm.html
{% extends 'blog_admin/base.html' %}
{% block title %}Categories{% endblock %}
{% block content %}
<div class="text-center mt-3">
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
</div>

{% endblock %}

Blog/blogapp/templates/blogapp/delete_post.html
{% extends 'blogapp/base.html' %}
{% block title %}Add Post{% endblock %}
{% block content %}
    <h1>Delete Blog Post</h1>
    <h3>Delete: {{post.title}} </h3>
    <div class="form-group">
        <form action="" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Delete"> 
            <a href="{% url 'home' %}" class="btn btn-secondary">Home</a>
        </form>
    </div>
    

       
 
{% endblock %}

Blog/blogapp/templates/blogapp/edit_post.html
{% extends 'blogapp/base.html' %}
{% block title %}Edit post{% endblock %}
{% block content %}
    <h1 class="text-center mt-3" >Edit Blog Post</h1>
    <div class="form-group">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Save"> 
            <a href="{% url 'home' %}" class="btn btn-secondary">Back</a>
        </form>
    </div>
    

       
 
{% endblock %}

Blog/blogapp/templates/blogapp/home.html
{% extends 'blogapp/base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="mt-2">
    <h1 class="text-center">Blogs</h1>
</div>

<div class="text-center mt-5 border border-primary p-4 ">
    <form action="">
        {{myFilter.form}}
        <button class="btn btn-primary" type="submit">Search</button>
    </form>
</div>

<div class="mt-5">
    {% if is_paginated %}
        {% for post in page_obj %}
        <ul>
            <li>
                <div class="mt-5">
                   <h1> <a href="{% url 'article' post.id %}" >{{post.title}}</a> </h1>- <a
                        href="{% url 'category' post.category.id %}"> ({{post.category}}).</a>
                    Author-{{post.author.first_name}}
                    {{post.author.last_name}}<br>
                    <div class="border">
                        {{post.body|safe|truncatewords:80}}...
                    </div>
                    <hr>
                </div>
            </li>
        </ul>
        {% endfor %}
        <div>
            {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previous_page_number}}">Previous</a>
            {% endif %}
            <span>Page {{page_obj.number}} of {{page_obj.paginator.num_pages}} </span>
            {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}">Next</a>
            {% endif %}
        </div>
    {% else %}
        <ul>
            {% for post in object_list %}
                <li>
                    <div class="mt-4">
                        <a href="{% url 'article' post.id %}">{{post.title}}</a> - <a
                            href="{% url 'category' post.category.id %}"> ({{post.category}}).</a>
                        Author-{{post.author.first_name}}
                        {{post.author.last_name}}<br>
                        <div class="border border-warning">
                            {{post.body|safe|truncatewords:80}}...
                        </div>
                        <hr>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>

{% endblock %}

Blog/blogapp/templates/blogapp/myposts.html
{% extends 'blogapp/base.html' %}
{% block title %}My Posts{% endblock %}
{% block content %}
<h1 class="text-center mt-3">My Post</h1>
{% if object_list %}
<div class="text-center mt-5 border border-primary p-4 ">
    <form action="">
        {{myFilter.form}}
        <button class="btn btn-primary" type="submit">Search</button>
    </form>
</div>
{% endif %}
<div class="container mt-5">
    <div class="row text-center">
        {% if object_list %}
        <div class="col-md-8"><h4>Posts</h4></div>
        <div class="col-md-4"><h4>Action</h4></div>
        <hr>
    </div>
    <ol>
        {% for post in object_list %}
       
        <li>
            <div class="row mt-4 ">
                <div class="col-md-8">
                    <a href="{% url 'article' post.id %}">{{post.title}}</a> - <a
                        href="{% url 'category' post.category.id %}">{{post.category}}</a> -
                    {{post.author.first_name}} {{post.author.last_name}}<br>
                    <div class="text-justify">
                        {{post.body|safe|truncatewords:30}}...
                    </div>
                </div>
                <div class="col-md-4 text-center">
                    <a href="{% url 'edit_post' post.pk %}">Update</a> | 
                    <a href="{% url 'delete_post' post.pk %}">Delete</a>     
                </div>
            </div>
            <hr>
        </li>
        {% endfor %}

    </ol>
    {% else%}
    <h2>You don't have any post ...  <a href="{% url 'add_post' %}">add one</a></h2>
    {% endif%}
</div>
<div class="mt-5">

</div>

{% endblock %}